# Generated by Django 4.1.4 on 2023-10-27 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_secobject_usermisc_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('mac', models.CharField(max_length=128)),
                ('status', models.IntegerField(default=0)),
                ('power', models.IntegerField(default=0)),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.secobject')),
            ],
        ),
    ]
