# Generated by Django 4.1.4 on 2023-10-27 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_lockmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockmodel',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 27, 14, 10, 37, 290745)),
        ),
    ]
