# Generated by Django 5.0 on 2023-12-05 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_lockmodel_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockmodel',
            name='command',
            field=models.CharField(default='none', max_length=64),
        ),
        migrations.AddField(
            model_name='lockmodel',
            name='inverse',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lockmodel',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 15, 15, 14, 182434)),
        ),
    ]
