# Generated by Django 5.0 on 2023-12-05 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_lockmodel_command_lockmodel_inverse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockmodel',
            name='state',
            field=models.CharField(default='Закрыт', max_length=64),
        ),
        migrations.AlterField(
            model_name='lockmodel',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 16, 30, 27, 195817)),
        ),
    ]
