# Generated by Django 5.0 on 2023-12-05 14:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_lockmodel_state_alter_lockmodel_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockmodel',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 17, 35, 7, 1684)),
        ),
        migrations.CreateModel(
            name='CameraModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('rtsp', models.CharField(max_length=128)),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.secobject')),
            ],
        ),
    ]
